//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace HumberShores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int app_id { get; set; }
        public int patient_id { get; set; }
        public int emp_id { get; set; }
        public System.DateTime app_date { get; set; }

        [ConcurrencyCheck]
        public System.TimeSpan app_time { get; set; }

        public string app_reason { get; set; }
        public string app_comment { get; set; }
        public bool app_child { get; set; }
        public string app_child_first { get; set; }
        public string app_child_last { get; set; }
        public Nullable<System.DateTime> app_child_dob { get; set; }
        public string app_child_gender { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual site_users site_users { get; set; }
    }
}
