//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberShores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPITAL_FEEDBACK
    {
        public int id_feedback { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string contact_email { get; set; }
        public string type_feedback { get; set; }
        public string depart_feedback { get; set; }
        public string comment_feedback { get; set; }
        public System.DateTime date_feedback { get; set; }
        public byte is_publish { get; set; }
    }
}
