//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberShores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPITAL_VACANCY
    {
        public int vacancy_id { get; set; }
        public string job_title { get; set; }
        public System.DateTime apply_due_date { get; set; }
        public string description { get; set; }
        public int description_id { get; set; }
        public string job_type { get; set; }
        public Nullable<int> no_of_vacancy { get; set; }
        public string contact_email { get; set; }
    }
}
