//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberShores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MattDatabaseEntities : DbContext
    {
        public MattDatabaseEntities()
            : base("name=MattDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<announcement> announcements { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<site_roles> site_roles { get; set; }
        public virtual DbSet<site_users> site_users { get; set; }
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<HOSPITAL_FEEDBACK> HOSPITAL_FEEDBACK { get; set; }
        public virtual DbSet<HOSPITAL_VACANCY> HOSPITAL_VACANCY { get; set; }
        public virtual DbSet<OPPORTUNITY> OPPORTUNITies { get; set; }
        public virtual DbSet<VOLUNTEER> VOLUNTEERs { get; set; }
        public virtual DbSet<PASS> PASSes { get; set; }
        public virtual DbSet<PASS_TYPE> PASS_TYPE { get; set; }
        public virtual DbSet<VEHICLE> VEHICLES { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<specialty> specialties { get; set; }
        public virtual DbSet<physician> physicians { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<property_sections> property_sections { get; set; }
    }
}
