//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberShores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician
    {
        public int doctor_id { get; set; }
        public int emp_id { get; set; }
        public int department_id { get; set; }
        public Nullable<int> special1 { get; set; }
        public Nullable<int> special2 { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string street_address1 { get; set; }
        public string street_address2 { get; set; }
        public string building_name { get; set; }
        public string city { get; set; }
        public Nullable<int> province { get; set; }
        public string postal_code { get; set; }
        public Nullable<int> user_id { get; set; }
        public string fax { get; set; }
    
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
        public virtual province province1 { get; set; }
        public virtual specialty specialty { get; set; }
        public virtual specialty specialty1 { get; set; }
        public virtual site_users site_users { get; set; }
    }
}
