//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberShores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public site_users()
        {
            this.announcements = new HashSet<announcement>();
            this.employees = new HashSet<employee>();
            this.appointments = new HashSet<appointment>();
            this.PASSes = new HashSet<PASS>();
            this.VEHICLES = new HashSet<VEHICLE>();
            this.physicians = new HashSet<physician>();
        }
    
        public int user_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string role_code { get; set; }
        public string user_first_name { get; set; }
        public string user_last_name { get; set; }
        public System.DateTime user_dob { get; set; }
        public string user_gender { get; set; }
        public string user_address { get; set; }
        public string user_city { get; set; }
        public string user_province { get; set; }
        public string user_postal_code { get; set; }
        public string user_email { get; set; }
        public string user_username { get; set; }
        public string user_password { get; set; }
        public string user_phone { get; set; }
        public System.DateTime user_date_joined { get; set; }

		public string full_name
		{
			get
			{
				return this.user_first_name + " " + this.user_last_name;
			}
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<announcement> announcements { get; set; }
        public virtual employee employee { get; set; }
        public virtual site_roles site_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASS> PASSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE> VEHICLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<physician> physicians { get; set; }
    }
}
