//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberShores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE
    {
        public string LICENSE_NUMBER { get; set; }
        public int USER_ID { get; set; }
        public string MAKE { get; set; }
        public string MODEL { get; set; }
        public Nullable<System.DateTime> YEAR { get; set; }
    
        public virtual site_users site_users { get; set; }
    }
}
