//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumberShores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLUNTEER
    {
        public int VOLUNTEER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string OCCUPATION { get; set; }
        public int OPPORTUNITY_ID { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string PROVINCE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public string GENDER { get; set; }
        public string LICENCE { get; set; }
        public System.DateTime START_DATE { get; set; }
    
        public virtual OPPORTUNITY OPPORTUNITY { get; set; }
    }
}
